
from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path

import cv2

from crypto import decrypt_image, encrypt_image
from metrics import correlation_coefficients, entropy, npcr, uaci
from report import generate_report

VALID_EXTS = {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff", ".webp"}

def _load_image(path: Path):
    image = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if image is None:
        raise ValueError(f"Cannot read image: {path}")
    return image

def _build_record(name, left_title, right_title, left_image, right_image, extra1, extra2, extra3):
    return {
        "name": name,
        "left_title": left_title,
        "right_title": right_title,
        "left_image": left_image,
        "right_image": right_image,
        "left_entropy": entropy(left_image),
        "right_entropy": entropy(right_image),
        "left_corr": correlation_coefficients(left_image),
        "right_corr": correlation_coefficients(right_image),
        "extra_line1": extra1,
        "extra_line2": extra2,
        "extra_line3": extra3,
    }

def _make_run_dir(output_root: Path, mode: str) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = output_root / f"{mode}_{timestamp}"
    run_dir.mkdir(parents=True, exist_ok=True)
    return run_dir

def process_encrypt(file_path: Path, run_dir: Path) -> Path:
    original = _load_image(file_path)
    encrypted = encrypt_image(original)
    cv2.imwrite(str(run_dir / f"encrypted_{file_path.stem}.png"), encrypted)

    records = [
        _build_record(
            file_path.name,
            "Original Image",
            "Encrypted Image",
            original,
            encrypted,
            f"NPCR (Original vs Encrypted): {npcr(original, encrypted):.2f}%",
            f"UACI (Original vs Encrypted): {uaci(original, encrypted):.2f}%",
            "Mode: ENCRYPT",
        )
    ]
    return generate_report(records, run_dir / "encryption_report.docx", "Encryption Report")

def process_decrypt(file_path: Path, run_dir: Path) -> Path:
    encrypted = _load_image(file_path)
    decrypted = decrypt_image(encrypted)
    cv2.imwrite(str(run_dir / f"decrypted_{file_path.stem}.png"), decrypted)

    records = [
        _build_record(
            file_path.name,
            "Encrypted Image",
            "Decrypted Image",
            encrypted,
            decrypted,
            f"Decryption check: {'PASS' if decrypted.shape == encrypted.shape else 'FAIL'}",
            "Mode: DECRYPT",
            "Use the encrypted file generated by the encrypt mode.",
        )
    ]
    return generate_report(records, run_dir / "decryption_report.docx", "Decryption Report")

def main() -> int:
    parser = argparse.ArgumentParser(description="Encrypt or decrypt a single image file and generate a report.")
    parser.add_argument("-m", "--mode", choices=["encrypt", "decrypt"], required=True, help="Choose operation mode.")
    parser.add_argument("-f", "--file", required=True, help="Path of the image file to process.")
    parser.add_argument("-o", "--output", default="output", help="Root output folder for results.")
    args = parser.parse_args()

    file_path = Path(args.file)
    output_root = Path(args.output)

    if not file_path.exists() or not file_path.is_file():
        print(f"Error: file not found: {file_path}")
        return 1

    if file_path.suffix.lower() not in VALID_EXTS:
        print(f"Error: unsupported file type: {file_path.suffix}")
        return 1

    run_dir = _make_run_dir(output_root, args.mode)

    try:
        if args.mode == "encrypt":
            report = process_encrypt(file_path, run_dir)
        else:
            report = process_decrypt(file_path, run_dir)
    except Exception as exc:
        print(f"Error: {exc}")
        return 1

    print(f"Run output folder: {run_dir}")
    print(f"Report created: {report}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
